print("My name is  Kang'ethu")
print("i am  18 years old")
print("i am from home")
print("I love law but i cant")
print ("my pc is messing me up")
print("-----------")
print("************")
print("##############")